name       : haskell-lifted-async
version    : 0.10.0.6
release    : 3
source     :
    - https://hackage.haskell.org/package/lifted-async-0.10.0.6/lifted-async-0.10.0.6.tar.gz : 72f5563fc622fe0e218e393287c49a63eec7207330cd9fdbe73416db745ad0da
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides IO operations from async package lifted to any instance of MonadBase or MonadBaseControl.
description: |
    This package provides IO operations from async package lifted to any instance of MonadBase or MonadBaseControl.
builddeps  :
    - haskell-async-devel
    - haskell-cabal-install
    - haskell-constraints-devel
    - haskell-lifted-base-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-constraints-devel
        - haskell-lifted-base-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
