name       : haskell-lifted-async
version    : 0.10.0.2
release    : 2
source     :
    - https://hackage.haskell.org/package/lifted-async-0.10.0.2/lifted-async-0.10.0.2.tar.gz : 8ed740437f5ca16aa4d7508626cfa3da14f3305f292b0976a8a2072642c9e380
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides IO operations from async package lifted to any instance of MonadBase or MonadBaseControl.
description: "This package provides IO operations from async package lifted to any instance of MonadBase or MonadBaseControl. \n"
builddeps  :
    - haskell-async
    - haskell-cabal-install
    - haskell-constraints
    - haskell-lifted-base
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
