name       : haskell-lifted-async
version    : 0.9.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/lifted-async-0.9.1.1/lifted-async-0.9.1.1.tar.gz : 31ac44b834723c9b9d40a319135a712802f2690d700df283d0a380fcd8d48e40
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides IO operations from async package lifted to any instance of MonadBase or MonadBaseControl. 
description: |
    This package provides IO operations from async package lifted to any instance of MonadBase or MonadBaseControl. 
builddeps  :
    - haskell-async
    - haskell-cabal-install
    - haskell-constraints
    - haskell-lifted-base
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
